# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 25.11.1
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_gnu
ampl-asl=1.0.0=h5888daf_2
asttokens=3.0.1=pypi_0
bzip2=1.0.8=hda65f42_8
ca-certificates=2025.11.12=hbd8a1cb_0
casadi=3.7.2=pypi_0
comm=0.2.3=pypi_0
contourpy=1.3.3=pypi_0
cycler=0.12.1=pypi_0
debugpy=1.8.19=pypi_0
decorator=5.2.1=pypi_0
dill=0.4.0=pypi_0
et-xmlfile=2.0.0=pypi_0
executing=2.2.1=pypi_0
flexcache=0.3=pypi_0
flexparser=0.4=pypi_0
fonttools=4.61.1=pypi_0
glpk=5.0=h445213a_0
gmp=6.3.0=hac33072_2
icu=78.1=h33c6efd_0
ipopt=3.14.19=h6c08d29_1
ipykernel=7.1.0=pypi_0
ipython=9.8.0=pypi_0
ipython-pygments-lexers=1.1.1=pypi_0
jedi=0.19.2=pypi_0
joblib=1.5.3=pypi_0
jupyter-client=8.7.0=pypi_0
jupyter-core=5.9.1=pypi_0
kiwisolver=1.4.9=pypi_0
ld_impl_linux-64=2.45=default_hbd61a6d_105
libblas=3.11.0=7_hc00574d_netlib
libcblas=3.11.0=7_h8e06fc2_netlib
libexpat=2.7.3=hecca717_0
libffi=3.5.2=h9ec8514_0
libgcc=15.2.0=he0feb66_16
libgcc-ng=15.2.0=h69a702a_16
libgfortran=15.2.0=h69a702a_16
libgfortran5=15.2.0=h68bc16d_16
libgomp=15.2.0=he0feb66_16
libhwloc=2.12.1=default_hafda6a7_1003
libiconv=1.18=h3b78370_2
liblapack=3.11.0=7_h8876d29_netlib
liblzma=5.8.1=hb9d3cd8_2
libnsl=2.0.1=hb9d3cd8_1
libscotch=7.0.10=int32_h8512f2c_2
libspral=2025.05.20=hfabd9d1_1
libsqlite=3.51.1=hf4e2dac_1
libstdcxx=15.2.0=h934c35e_16
libstdcxx-ng=15.2.0=hdf11a46_16
libuuid=2.41.3=h5347b49_0
libxcrypt=4.4.36=hd590300_1
libxml2=2.15.1=he237659_1
libxml2-16=2.15.1=hca6bf5a_1
libzlib=1.3.1=hb9d3cd8_2
linear-tree=0.3.5=pypi_0
matplotlib=3.10.8=pypi_0
matplotlib-inline=0.2.1=pypi_0
metis=5.1.0=hd0bcaf9_1007
mpmath=1.3.0=pypi_0
mumps-include=5.8.1=h1795ed4_4
mumps-seq=5.8.1=h4374b6a_4
narwhals=2.14.0=pypi_0
ncurses=6.5=h2d0b736_3
nest-asyncio=1.6.0=pypi_0
networkx=3.6.1=pypi_0
numdifftools=0.9.42=pypi_0
numpy=2.4.0=pypi_0
openpyxl=3.1.5=pypi_0
openssl=3.6.0=h26f9b46_0
packaging=25.0=pypi_0
pandas=2.3.3=pypi_0
parso=0.8.5=pypi_0
pexpect=4.9.0=pypi_0
pillow=12.0.0=pypi_0
pint=0.25.2=pypi_0
pip=25.3=pyh8b19718_0
platformdirs=4.5.1=pypi_0
plotly=6.5.0=pypi_0
ply=3.11=pyhd8ed1ab_3
prompt-toolkit=3.0.52=pypi_0
psutil=7.2.1=pypi_0
ptyprocess=0.7.0=pypi_0
pure-eval=0.2.3=pypi_0
pygments=2.19.2=pypi_0
pymysql=1.1.2=pypi_0
pyodbc=5.3.0=pypi_0
pyomo=6.9.5=py311h1ddb823_0
pyparsing=3.3.1=pypi_0
pyro4=4.82=pypi_0
python=3.11.14=hd63d673_2_cpython
python-dateutil=2.9.0.post0=pypi_0
python-louvain=0.16=pypi_0
python_abi=3.11=8_cp311
pytz=2025.2=pypi_0
pyyaml=6.0.3=pypi_0
pyzmq=27.1.0=pypi_0
qtconsole=5.7.0=pypi_0
qtpy=2.4.3=pypi_0
readline=8.3=h853b02a_0
scikit-learn=1.6.1=pypi_0
scipy=1.16.3=pypi_0
seaborn=0.13.2=pypi_0
serpent=1.42=pypi_0
setuptools=80.9.0=pyhff2d567_0
six=1.17.0=pypi_0
stack-data=0.6.3=pypi_0
sympy=1.14.0=pypi_0
threadpoolctl=3.6.0=pypi_0
tk=8.6.13=noxft_ha0e22de_103
tornado=6.5.4=pypi_0
traitlets=5.14.3=pypi_0
typing-extensions=4.15.0=pypi_0
tzdata=2025.3=pypi_0
wcwidth=0.2.14=pypi_0
wheel=0.45.1=pyhd8ed1ab_1
xlrd=2.0.2=pypi_0
z3-solver=4.15.4.0=pypi_0
zstd=1.5.7=hb78ec9c_6
